#!/bin/bash
# This script runs all .ggb files from ../docs/import/ggb-benchmarks,
# proves them via the GDD method and saves the proof tree as .gv and .png in ../docs.

# Run this script with
# xvfb-run -a -s "-screen 0 1280x800x24" ./import-ggb-prove-gdd-export-gv-png
# to hide the graphical input.

# This script accepts the argument "local" or "snap" to choose
# the required executable. "local" uses Gradle to recompile the program on each run.
# "snap" uses the snapcraft installation and considered therefore faster.

BENCHMARKS_FOLDER=../docs/import/ggb-benchmarks # this may be changed on demand
TIMEOUT=5 # JGEX forgets to quit sometimes, this timeout ensures proper exit

test -x $BENCHMARKS_FOLDER || {
 echo "No folder $BENCHMARKS_FOLDER exists."
 echo "Consider downloading some (or all) from e.g. https://github.com/kovzol/geogebra/tree/master/test/scripts/benchmark/prover/tests/true first, then retry."
 exit 1
 }

MYDIR=`pwd`
WARNING_COLOR="\033[91m"
RESUME_COLOR="\033[0m"

if [ "$1" != "local" -a "$1" != "snap" -a "$1" != "" ]; then
 echo "Unsupported parameter: $1"
 exit 2
 fi

if [ "$1" = "local" -o "$1" = "" ]; then
 GV_DIR=../..
 pushd ../.. >/dev/null
 echo "Building jgex via Gradle first (silently)"
 ./gradlew -q installDist
 popd >/dev/null
else
 JGEX_SNAP=`which jgex` && {
  echo "Using jgex from snap ($JGEX_SNAP)"
  } || {
  echo "JGEX is not installed. Consider installing it from https://snapcraft.io/jgex."
  exit 3
  }
 GV_DIR=~/snap/jgex/current/.jgex
 fi

for FULLNAME in `find $BENCHMARKS_FOLDER -name '*.ggb' | sort`; do
 NAME=`basename $FULLNAME .ggb`
 GV=$GV_DIR/$NAME.gv
 if [ "$1" = "snap" ]; then
  /bin/time -o ../docs/$NAME.txt /usr/bin/timeout -k $((TIMEOUT+1)) $TIMEOUT jgex -p gdd -o $NAME.gv -x $MYDIR/$FULLNAME > ../docs/$NAME.log 2>&1
 else
  pushd ../.. >/dev/null
  RUNTIME=`pwd`/build/install/jgex/bin/Java-Geometry-Expert
  /bin/time -o src/docs/$NAME.txt /usr/bin/timeout -k $((TIMEOUT+1)) $TIMEOUT $RUNTIME -p gdd -o $NAME.gv -x $MYDIR/$FULLNAME > src/docs/$NAME.log 2>&1
  popd >/dev/null
  fi
 PROBLEM=`cat ../docs/$NAME.log | grep "Unimplemented\|Unidentified\|Exception" | head -1`
 test -s $GV && {
  MD5SUM=`md5sum $GV | cut -f1 -d" "`
  if [ "$MD5SUM" = "d872444bcef19cb5462bb9a4fb4e9fb3" -o "$MD5SUM" = "3c964068bf7b811e7570449adc59af0e" -o "$MD5SUM" = "dd5ece2abd55b6f9b27df4df90e66fdf" ]; then
   echo -e "$WARNING_COLOR$NAME unsuccessful: empty gv tree, $PROBLEM$RESUME_COLOR"
  else
   dot -Tpng $GV > ../docs/$NAME.png
   LENGTH=`cat $GV | wc -l`
   echo "$NAME successful: $LENGTH lines of gv output"
   fi
  } || {
  echo -e "$WARNING_COLOR$NAME unsuccessful: $PROBLEM$RESUME_COLOR"
  }
 done
